### ISSUE TITLE
calibrate and predict scenario 01

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/MEGADAPT#9]
generar los .tiff con la proyección EPSG:32614

**Comment by serranoycandela** [comment]
@edithvilla puedes checar que la proyección de los tiffs es correcta y carga automáticamente?
yo lo probé en QGIS y ArcMap y funcionó

los archivos están en MEGADAPT_integracion/CarpetasTrabajo/Fidel/scenario01

el grupo 9 es el control (toda la región)

**Comment by edithvilla** [comment]
Confirmo que se pueden abrir en arcmap sin complicaciones
